name: Archive Task

permissions:
  contents: write

on:
  schedule:
    - cron: '30 12-13 * * 1,3,4,6' # https://crontab.guru/#30_12-13_*_*_1,4,6 21:30 JST (UTC+9)
    - cron: '0 6-7 * * 6' # https://crontab.guru/#0_6-7_*_*_6 # 15:00 JST (UTC+9)
    - cron: '20 9 * * 1' # https://crontab.guru/#20_9_*_*_1 # 18:20 JST (UTC+9) for fes live
  workflow_dispatch:
    # Allow manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Make script executable
      run: chmod +x scripts/archive_task.sh
    
    - name: Run archive task
      env:
        PLAYER_ID: ${{ secrets.PLAYER_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ARCHIVE_JSON: ${{ github.workspace }}/data/archive.json
      run: ./scripts/archive_task.sh

    - name: Get the current date time
      id: datetime
      run: echo "time_now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'auto(${{ steps.datetime.outputs.time_now }}): Update archive.json'
        add: |
          - data/archive.json