name: Archive Task

permissions:
  contents: write

on:
  workflow_dispatch:
    # Allow manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.time_now }}
      commit_timestamp: ${{ steps.commit_info.outputs.commit_timestamp }}
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Make script executable
      run: chmod +x scripts/archive_task.sh
    
    - name: Run archive task
      env:
        PLAYER_ID: ${{ secrets.PLAYER_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ARCHIVE_JSON: ${{ github.workspace }}/data/archive.json
      run: ./scripts/archive_task.sh

    - name: Check if updates were found
      id: check_updates
      run: |
        if [ -f "/tmp/has_updates" ]; then
          has_updates=$(cat /tmp/has_updates)
          echo "has_updates=$has_updates" >> $GITHUB_OUTPUT
          echo "Archive task found updates: $has_updates"
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
          echo "No updates file found, assuming no updates"
        fi

    - name: Get the current date time
      id: datetime
      if: steps.check_updates.outputs.has_updates == 'true'
      run: echo "time_now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.check_updates.outputs.has_updates == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'auto(${{ steps.datetime.outputs.time_now }}): Update archive info'
        add: |
          - data/archive.json
          - data/archive-details.json

    - name: Get commit timestamp for follow-up jobs
      id: commit_info
      run: |
        # Get the timestamp of the latest commit after potential new commit
        latest_commit_time=$(git log -1 --format=%ct)
        echo "commit_timestamp=$latest_commit_time" >> $GITHUB_OUTPUT
        echo "Latest commit timestamp: $latest_commit_time"

  auto-upload:
    runs-on: ubuntu-latest
    needs: archive
    if: ${{ success() && needs.archive.outputs.has_updates == 'true' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: 'main'
        fetch-depth: 2  # 需要获取前两个提交来比较差异
    
    - name: Setup Python and dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: pip install requests
    
    - name: Make script executable and run upload task
      env:
        R2_BUCKET: ${{ secrets.R2_BUCKET }}
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        chmod +x scripts/auto_upload_task.sh
        ./scripts/auto_upload_task.sh

  notification:
    runs-on: ubuntu-latest
    needs: archive
    if: ${{ success() && needs.archive.outputs.has_updates == 'true' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: 'main'
        fetch-depth: 2  # 需要获取前两个提交来比较差异
    
    - name: Setup Python and dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: pip install requests

    # - name: Bypass Cloudflare for GitHub Action
    #   uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.1.1
    #   with:
    #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
    #     cf_api_token: ${{ secrets.CF_API_TOKEN }}

    - name: Make script executable and run notification task
      env:
        QQ_BOT_URL: ${{ secrets.QQ_BOT_URL }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        QQ_BOT_HOST: ${{ secrets.QQ_BOT_HOST }}
      run: |
        chmod +x scripts/notification_task.sh
        ./scripts/notification_task.sh
