name: Archive Task

on:
  schedule:
    - cron: '30 12 * * 1,3,4,6' # https://crontab.guru/#30_12_*_*_1,4,6 21:30 JST (UTC+9)
    - cron: '0 6 * * 6' # https://crontab.guru/#0_6_*_*_6 # 15:00 JST (UTC+9)
  workflow_dispatch:
    # Allow manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Make script executable
      run: chmod +x scripts/archive_task.sh
    
    - name: Run archive task
      env:
        PLAYER_ID: ${{ secrets.PLAYER_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ARCHIVE_JSON: ${{ github.workspace }}/data/archive.json
      run: ./scripts/archive_task.sh

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: |
          - ${{ github.workspace }}/data/archive.json