name: Archive Task

on:
  schedule:
    # Run daily at 2:00 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Make script executable
      run: chmod +x scripts/archive_task.sh
    
    - name: Run archive task
      env:
        PLAYER_ID: ${{ secrets.PLAYER_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ARCHIVE_JSON: ${{ github.workspace }}/data/archive.json
      run: ./scripts/archive_task.sh