name: Notification Task

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Archive Task"]
    types:
      - completed

jobs:
  notification:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Check if latest commit is within 1 minute
      id: check_commit_time
      run: |
        # Get the timestamp of the latest commit
        latest_commit_time=$(git log -1 --format=%ct)
        current_time=$(date +%s)
        time_diff=$((current_time - latest_commit_time))
        
        echo "Latest commit time: $latest_commit_time"
        echo "Current time: $current_time"
        echo "Time difference: $time_diff seconds"
        
        # Check if commit is within 1 minute (60 seconds)
        if [ $time_diff -le 60 ]; then
          echo "Commit is within 1 minute, proceeding with notification task"
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "Commit is older than 1 minute, skipping notification task"
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Setup Python
      if: steps.check_commit_time.outputs.should_run == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      if: steps.check_commit_time.outputs.should_run == 'true'
      run: pip install requests
    
    - name: Make script executable
      if: steps.check_commit_time.outputs.should_run == 'true'
      run: chmod +x scripts/notification_task.sh
    
    - name: Run notification task
      if: steps.check_commit_time.outputs.should_run == 'true'
      env:
        QQ_BOT_URL: ${{ secrets.QQ_BOT_URL }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      run: ./scripts/notification_task.sh